### ISSUE TITLE
Issue with Server Timeout

### ISSUE THREAD

**Issue by HarvardYard** [siegrest/Pricer#8]
[19:49:50][ERROR] System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at Pricer.PriceManager.SearchPoePrices(String rawItemData)

Been running into this today. Similar issues with PoE Trade Macro as well.

**Comment by siegrest** [comment]
Seems to have been a temporary issue with https://www.poeprices.info/ when pricing non-uniques. As far as I know, TradeMacro uses the same service. Though, it was working fine for me just now.

**Comment by siegrest** [comment]
Closed due to inactivity
